//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CGWork.rc
//
#define ID_BUTTON_BROWSE                3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_CGWorkTYPE                  129
#define IDD_LIGHTS_DLG                  134
#define IDD_MATERIAL_DLG                136
#define IDD_COLOR_DLG                   139
#define IDD_PRESPECTIVE_DIALOG          141
#define IDD_SENS_DLG                    142
#define IDD_RESOLUTION_DLG              143
#define IDD_SENSITIVITY_DLG             145
#define IDD_SAVE_IMAGE_DLG              148
#define IDD_DIALOG_SILHOUETTE           150
#define IDD_DIALOG_FOG                  153
#define IDD_ANTIALIAS_DLG               155
#define IDC_LIGHT_SPACE                 1010
#define IDC_RADIO_LIGHT1                1017
#define IDC_RADIO_LIGHT2                1018
#define IDC_RADIO_LIGHT3                1019
#define IDC_RADIO_LIGHT4                1020
#define IDC_RADIO_LIGHT5                1021
#define IDC_RADIO_LIGHT6                1022
#define IDC_RADIO_LIGHT7                1023
#define IDC_RADIO_LIGHT8                1024
#define IDC_AMBL_COLOR_R                1025
#define IDC_LIGHT_ENABLED               1026
#define IDC_AMBL_COLOR_G                1027
#define IDC_AMBL_COLOR_B                1028
#define IDC_LIGHT_COLOR_R               1029
#define IDC_LIGHT_COLOR_G               1030
#define IDC_LIGHT_COLOR_B               1031
#define IDC_LIGHT_POS_X                 1032
#define IDC_LIGHT_POS_Y                 1033
#define IDC_LIGHT_POS_Z                 1034
#define IDC_LIGHT_DIR_X                 1035
#define IDC_LIGHT_DIR_Y                 1036
#define IDC_LIGHT_DIR_Z                 1037
#define IDC_LIGHT_TYPE                  1038
#define IDC_MATERIAL_AMBIENT            1039
#define IDC_MATERIAL_AMBIENT_R          1039
#define IDC_LIGHT_OUT_CONE_ANG          1039
#define IDC_MATERIAL_DIFFUSE            1040
#define IDC_WIREFRAME_COLOR_BUTTON      1040
#define IDC_MATERIAL_AMBIENT_B          1040
#define IDC_MATERIAL_SHININESS          1041
#define IDC_NORMAL_COLOR_BUTTON         1041
#define IDC_MATERIAL_SHININESS_R        1041
#define IDC_LIGHT_IN_CONE_ANG           1041
#define IDC_MATERIAL_SPECULAR           1042
#define IDC_BACKGROUND_COLOR_BUTTON     1042
#define IDC_DISCO_MODE_CHECK            1043
#define IDC_MATERIAL_AMBIENT_G          1043
#define IDC_IS_DISCO_CHECKBOX           1044
#define IDC_MATERIAL_DIFFUSE_R          1044
#define IDC_EDIT_NEAR                   1045
#define IDC_MATERIAL_DIFFUSE_G          1045
#define IDC_EDIT2                       1046
#define IDC_EDIT_FOV                    1046
#define IDC_MATERIAL_DIFFUSE_B          1046
#define IDC_EXPORT_WIDTH                1046
#define IDC_EDIT_FAR                    1047
#define IDC_MATERIAL_SHININESS_G        1047
#define IDC_MATERIAL_SHININESS_B        1048
#define IDC_EDIT_TESS                   1056
#define IDC_EDIT_ROT                    1057
#define IDC_EDIT_TRANS                  1058
#define IDC_HEIGHT                      1058
#define IDC_EXPORT_HEIGHT               1058
#define IDC_EDIT_SCALE                  1059
#define IDC_BUTTON_SIL_COLOR            1059
#define IDC_EDIT_SIL_THICKNESS          1060
#define IDC_RADIO_ATT_NONE              1061
#define IDC_RADIO_ATT_LINEAR            1062
#define IDC_RADIO_ATT_POW2              1063
#define IDC_CHECK1                      1064
#define IDC_CHECK_SOFT_SPOT             1064
#define IDC_BUTTON_FOG_COLOR            1065
#define IDC_EDIT_FOG_MIN_DIST           1066
#define IDC_EDIT_FOG_MAX_DIST           1067
#define IDC_RADIO_FOG_LINEAR            1068
#define IDC_RADIO_FOG_EXP               1069
#define IDC_FILTER_TYPE                 1069
#define IDC_RADIO_FOG_EXP_SQUARED       1070
#define IDC_FILTER_SIZE                 1070
#define IDC_EDIT_FOG_EXP_FACT           1071
#define ID_FILE_LOAD                    32771
#define ID_VIEW_ORTHOGRAPHIC            32772
#define ID_VIEW_PERSPECTIVE             32773
#define ID_ACTION_ROTATE                32774
#define ID_ACTION_TRANSLATE             32775
#define ID_ACTION_SCALE                 32776
#define ID_AXIS_X                       32777
#define ID_AXIS_Y                       32778
#define ID_AXIS_Z                       32779
#define ID_LIGHT_SHADING_FLAT           32781
#define ID_LIGHT_SHADING_GOURAUD        32782
#define ID_LIGHT_CONSTANTS              32783
#define ID_ANIM_PLAY                    32793
#define ID_ANIM_CLEAR                   32794
#define ID_ANIM_SNAPSHOT                32795
#define ID_BUTTON_SUBDIVIDE             32797
#define ID_OPTIONS_PERSPECTIVECONTROL   32798
#define ID_OPTIONS_MOUSESENSITIVITY     32799
#define ID_BBOX                         32801
#define ID_BUTTON_BBOX                  32801
#define ID_BUTTON32802                  32802
#define ID_BUTTON_VIEW                  32802
#define ID_BUTTON32803                  32803
#define ID_BUTTON_OBJECT                32803
#define ID_BUTTON32804                  32804
#define ID_BUTTON_POLY_NORM             32804
#define ID_BUTTON32806                  32806
#define ID_BUTTON_VERT_NORM             32806
#define ID_VIEW_NORMAL                  32807
#define ID_NORMAL_CALCULATED            32808
#define ID_NORMAL_FROMFILE              32809
#define ID_OPTIONS_TESSELLATIONTOLERANCE 32810
#define ID_BUTTON32812                  32812
#define ID_BUTTON_COLORS                32813
#define ID_ACTION_SELECT                32818
#define ID_ACTION_SELECT32819           32819
#define ID_SHADING_PHONG                32820
#define ID_LIGHT_SHADING_PHONG          32821
#define ID_RENDERING_WIREFRAME          32822
#define ID_RENDERING_SOLIDONSCREEN      32823
#define ID_RENDERING_SOLIDTOFILE        32824
#define ID_BUTTON_BCULLING              32826
#define ID_BUTTON_INVERSE_N             32827
#define ID_BUTTON_SIL                   32831
#define ID_RENDERING_BACKGROUND         32832
#define ID_BACKGROUND_OPEN              32833
#define ID_BACKGROUND_STRETCH           32834
#define ID_BACKGROUND_REPEAT            32835
#define ID_LIGHT_SETMATERIAL            32836
#define ID_OPTIONS_SILHOUETTEOPTIONS    32837
#define ID_BACKGROUND_CLEAR             32838
#define ID_RENDERING_FOGEFFECT          32839
#define ID_FOGEFFECT_ENABLE             32840
#define ID_FOGEFFECT_OPTIONS            32841
#define ID_ANIMATION_RECORD             32842
#define ID_ANIMATION_PLAY               32843
#define ID_ANIMATION_INTERPOLATION      32844
#define ID_INTERPOLATION_LINEAR         32845
#define ID_INTERPOLATION_BEZIER         32846
#define ID_ANIMATION_SAVETOIMAGES       32847
#define ID_ANIMATION_SPEED              32848
#define ID_PLAYBACKSPEED_INCREASEBY10   32849
#define ID_PLAYBACKSPEED_DECREASEBY10   32850
#define ID_PLAYBACKSPEED_NORMAL         32851
#define ID_PLAYBACKSPEED_INCREASE       32852
#define ID_PLAYBACKSPEED_DECREASE       32853
#define ID_RENDERING_ANTI               32854
#define ID_ANTI_ENABLED                 32855
#define ID_ANTI_OPTIONS                 32856
#define ID_ANTI_OPTIONS32857            32857
#define ID_FOGEFFECT_PORTAL             32858
#define ID_FILE_CLEARALL                32859

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32860
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
